apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agencyos-docs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - docs.agencyos.cc
      secretName: agencyos-docs-tls
  rules:
    - host: docs.agencyos.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: agencyos-docs
                port:
                  number: 80
